STANDARD_COLUMNS = [
    "date",
    "platform",
    "account_name",
    "campaign_name",
    "ad_group_name",
    "keyword",
    "product_name",
    "impressions",
    "clicks",
    "cost",
    "conversions",
    "revenue",
    "orders",
]

NUMERIC_COLUMNS = [
    "impressions",
    "clicks",
    "cost",
    "conversions",
    "revenue",
    "orders",
]

DIMENSION_COLUMNS = [
    "platform",
    "account_name",
    "campaign_name",
    "ad_group_name",
    "keyword",
    "product_name",
]

COLUMN_ALIASES = {
    "date": [
        "date",
        "day",
        "일자",
        "날짜",
        "기간",
        "보고일",
        "집행일",
        "집계일",
        "기준일",
        "광고일자",
        "보고기간",
        "월",
        "년월",
    ],
    "platform": [
        "platform",
        "media",
        "channel",
        "publisher",
        "매체",
        "플랫폼",
        "채널",
        "광고매체",
        "매체명",
        "사이트",
        "사이트명",
        "마켓",
        "마켓명",
        "판매채널",
        "광고채널",
    ],
    "account_name": [
        "account",
        "account name",
        "advertiser",
        "client",
        "계정",
        "계정명",
        "광고주",
        "광고주명",
        "회원사",
        "광고계정",
        "광고계정명",
        "판매자",
        "판매자명",
        "셀러",
        "셀러명",
        "상점명",
        "브랜드명",
    ],
    "campaign_name": [
        "campaign",
        "campaign name",
        "캠페인",
        "캠페인명",
        "광고명",
        "광고캠페인",
        "광고 캠페인",
        "광고캠페인명",
    ],
    "ad_group_name": [
        "ad group",
        "adgroup",
        "ad group name",
        "ad_group",
        "광고그룹",
        "광고그룹명",
        "그룹",
        "그룹명",
        "광고 그룹",
        "광고 그룹명",
    ],
    "keyword": [
        "keyword",
        "query",
        "search term",
        "키워드",
        "검색어",
        "검색 키워드",
        "키워드명",
        "입찰키워드",
        "입찰 키워드",
        "구매키워드",
        "구매 키워드",
    ],
    "product_name": [
        "product",
        "product name",
        "item",
        "sku",
        "상품",
        "상품명",
        "소재",
        "광고소재",
        "광고상품",
        "광고상품명",
        "광고 상품명",
        "노출상품명",
        "노출 상품명",
    ],
    "impressions": [
        "impressions",
        "impr",
        "views",
        "노출",
        "노출수",
        "조회",
        "광고노출수",
        "광고 노출수",
        "노출 횟수",
        "노출수(회)",
    ],
    "clicks": [
        "clicks",
        "click",
        "클릭",
        "클릭수",
        "광고클릭수",
        "광고 클릭수",
        "클릭 횟수",
        "클릭수(회)",
    ],
    "cost": [
        "cost",
        "spend",
        "amount spent",
        "ad cost",
        "광고비",
        "비용",
        "소진금액",
        "집행금액",
        "사용금액",
        "광고 비용",
        "광고비(원)",
        "총광고비",
        "총 광고비",
        "소진 광고비",
        "과금액",
        "과금금액",
    ],
    "conversions": [
        "conversions",
        "conversion",
        "purchase",
        "전환",
        "전환수",
        "구매",
        "구매수",
        "전환건수",
        "전환 건수",
        "구매건수",
        "구매 건수",
        "전환주문수",
        "전환 주문수",
    ],
    "revenue": [
        "revenue",
        "sales",
        "conversion value",
        "purchase value",
        "매출",
        "매출액",
        "전환매출",
        "구매금액",
        "광고매출",
        "광고 매출",
        "광고매출액",
        "총매출",
        "총 매출",
        "주문금액",
        "결제금액",
        "전환매출액",
        "매출액(원)",
    ],
    "orders": [
        "orders",
        "order",
        "주문",
        "주문수",
        "결제수",
        "주문건수",
        "주문 건수",
        "결제건수",
        "결제 건수",
    ],
}
